spring.application.name=auth-service

server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET_KEY}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

spring.management.endpoints.web.exposure.include=health,info

logging.pattern.level=%5p [${spring.application.name:},%X{correlationId}]